Add version attribute as action output
frenck/action-addon-information pull request #16
Opened 2021-05-24 19:25 UTC by Poeschl

During using the information addon, I was missing the version attribute. This PR adds it as additional output.

2021-05-25 07:17 UTC, frenck commented
I can see this being helpful for some add-ons structures, but in a CI/CD automated environment, it doesn't make much sense to me.

Versions should be defined by thinks like releases or git tags.

2021-05-25 07:35 UTC, Poeschl commented
I will use it as tags for my addons which is indeed not a good practice for releasing them. Since its still a freetime-project I have currently no motivation to come up with a complex release structure or splitted add-on repositories.

The version is also an basic attribute of an addon as well which could be used also in CI. Thinking about checks of matching versions of Changelog and config.json and automatic tag creation on master pushes.

2021-05-25 07:38 UTC, frenck requested changes
👍 

But needs adjustments to the README/documentation.

2021-05-25 07:39 UTC, Poeschl commented
Will do this evening.

2021-05-25 07:41 UTC, Poeschl commented
Ah, forget the comment before ;) 
* grabs full cup of coffee

2021-05-29 15:49 UTC, Poeschl commented
The prettier should now be happy as well

2021-05-30 08:06 UTC, frenck commented on README.md
> +|    `version`    |                 The version of the addon.                 |
```suggestion
|    `version`    |                 The version of the add-on.                 |
```

2021-05-30 08:08 UTC, frenck commented on README.md
> +|    `version`    |                 The version of the add-on.                 |
```suggestion
|    `version`    |                The version of the add-on.                 |
```

2021-05-30 08:09 UTC, frenck approved these changes
Thanks, @Poeschl 👍

2021-05-30 08:09 UTC, merged